openapi: "3.0.1"

info:
  title: "Register"
  version: "1"
  description: Register API

servers:
  - url: http://localhost:8080
    description: Local server

paths:

  /teacher:
    post:
      summary: Save Teacher
      operationId: saveTeacher
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'teacherSchemas.yml#/components/schemas/TeacherDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'teacherSchemas.yml#/components/schemas/TeacherDTO'

  /teacher/{id}:
    get:
      summary: Get Teacher By Id
      operationId: getTeacherById
      parameters:
        - name: id
          in: path
          description: Unique Id of an User
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'teacherSchemas.yml#/components/schemas/TeacherDTO'
  /child:
    post:
      summary: Save Child
      operationId: saveChild
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'childSchemas.yml#/components/schemas/ChildDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'childSchemas.yml#/components/schemas/ChildDTO'
  /child/{id}:
    get:
      summary: Get Child By Id
      operationId: getChildById
      parameters:
        - name: id
          in: path
          description: Unique Id of an Child
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'childSchemas.yml#/components/schemas/ChildDTO'

  /activity:
    post:
      summary: Save Activity
      operationId: saveActivity
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'activitySchemas.yml#/components/schemas/ActivityDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'activitySchemas.yml#/components/schemas/ActivityDTO'
  /activity/{id}:
    get:
      summary: Get Activity By Id
      operationId: getActivityById
      parameters:
        - name: id
          in: path
          description: Unique Id of an Activity
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'activitySchemas.yml#/components/schemas/ActivityDTO'
  /parent:
    post:
      summary: Save Parent
      operationId: saveParent
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'parentSchemas.yml#/components/schemas/ParentDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'parentSchemas.yml#/components/schemas/ParentDTO'
  /parent/{id}:
    get:
      summary: Get Parent By Id
      operationId: getParentById
      parameters:
        - name: id
          in: path
          description: Unique Id of an Parent
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'parentSchemas.yml#/components/schemas/ParentDTO'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
