openapi: "3.0.1"

info:
  title: "Register"
  version: "1"
  description: Register API

servers:
  - url: http://localhost:8080
    description: Local server

paths:

  /teacher:
    post:
      summary: Save Teacher
      operationId: saveTeacher
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'teacherSchemas.yml#/components/schemas/TeacherDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'teacherSchemas.yml#/components/schemas/TeacherDTO'

  /teacher/{id}:
    get:
      summary: Get Teacher By Id
      operationId: getTeacherById
      parameters:
        - name: id
          in: path
          description: Unique Id of an User
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'teacherSchemas.yml#/components/schemas/TeacherDTO'
  /child:
    post:
      summary: Save Child
      operationId: saveChild
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'childSchemas.yml#/components/schemas/ChildDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'childSchemas.yml#/components/schemas/ChildDTO'
  /child/{id}:
    get:
      summary: Get Child By Id
      operationId: getChildById
      parameters:
        - name: id
          in: path
          description: Unique Id of an Child
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'childSchemas.yml#/components/schemas/ChildDTO'

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
